api_key: lzxcdijjqvg7us4atgk58g8av8la13vj
cookie:
  expiry_days: 30
  key: my-random-key
  name: my-random-name
credentials:
  usernames:
    fabg:
      email: f.test@gmail.com
      first_name: Florian
      last_name: abgrall
      logged_in: false
      password: $2b$12$cO4EOZ3kcQ7jJmjnQpbTf.pBGPgGzRKKm3XtAdv2C9fOe5x9DPhpG
      password_hint: admin
      roles:
      - user
      - admin
    fabgrall:
      email: florian.abgrall750@gmail.com
      first_name: Florian
      last_name: ABGRALL
      logged_in: false
      password: $2b$12$jB20bN6XKIh7ahzPgdiC9uTY7xwL1eio3QxLWO6huul4v1dwpQBMa
      password_hint: admin
      roles:
      - user
      - admin
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      first_name: John
      last_name: Smith
      logged_in: false
      password: $2b$12$8ukAfDSgU9RaP2yBJRwF8uk2frpTkbYsprJTmq68raHiA4InQql.u
      roles:
      - admin
      - user
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      first_name: Rebecca
      last_name: Briggs
      logged_in: false
      password: $2b$12$GJKJ7GSxjWaEUGj3qFqHluE5xexAACd5OPjfm7TQRYqG4V5rJ2v6e
      roles:
      - user
oauth2:
  google:
    client_id: null
    client_secret: null
    redirect_uri: null
  microsoft:
    client_id: null
    client_secret: null
    redirect_uri: null
    tenant_id: null
pre-authorized:
  emails:
  - melsby@gmail.com
