api_key: lzxcdijjqvg7us4atgk58g8av8la13vj
cookie:
  expiry_days: 30
  key: my-random-key
  name: my-random-name
credentials:
  usernames:
    ashley.ball:
      email: ashley.ball@example.com
      first_name: Ashley
      last_name: Ball
      logged_in: false
      password: +1WlW
      password_hint: Country see fire.
      roles:
      - user
    jsmith:
      email: john.smith@test.com
      first_name: John
      last_name: Smith
      logged_in: false
      password: '123'
      password_hint: A very simple number...
      roles:
      - user
      - admin
    michael.liu:
      email: michael.liu@example.com
      first_name: Michael
      last_name: Liu
      logged_in: false
      password: '&4Zf@'
      password_hint: Card hair deal at.
      roles:
      - user
    rodney.cross:
      email: rodney.cross@example.com
      first_name: Rodney
      last_name: Cross
      logged_in: false
      password: 3@9Ts
      password_hint: On stay parent.
      roles:
      - user
    sherri.rocha:
      email: sherri.rocha@example.com
      first_name: Sherri
      last_name: Rocha
      logged_in: false
      password: '@1YGe'
      password_hint: Among yeah parent.
      roles:
      - user
oauth2:
  google:
    client_id: null
    client_secret: null
    redirect_uri: null
  microsoft:
    client_id: null
    client_secret: null
    redirect_uri: null
    tenant_id: null
pre-authorized:
  emails:
  - melsby@gmail.com
