api_key: lzxcdijjqvg7us4atgk58g8av8la13vj
cookie:
  expiry_days: 30
  key: my-random-key
  name: my-random-name
credentials:
  usernames:
    bailey.henderson:
      email: bailey.henderson@example.com
      first_name: Bailey
      last_name: Henderson
      logged_in: false
      password: '#4CGa'
      password_hint: Break wind nation shoulder several.
      roles:
      - user
    douglas.ramos:
      email: douglas.ramos@example.com
      first_name: Douglas
      last_name: Ramos
      logged_in: false
      password: j@8Cm
      password_hint: Despite daughter because.
      roles:
      - user
    elizabeth.williams:
      email: elizabeth.williams@example.com
      first_name: Elizabeth
      last_name: Williams
      logged_in: false
      password: a^6Yc
      password_hint: Republican best camera lose.
      roles:
      - user
    jsmith:
      email: john.smith@test.com
      first_name: John
      last_name: Smith
      logged_in: false
      password: '123'
      password_hint: A very simple number...
      roles:
      - user
      - admin
    michael.kramer:
      email: michael.kramer@example.com
      first_name: Michael
      last_name: Kramer
      logged_in: false
      password: '&4Io6'
      password_hint: Activity itself.
      roles:
      - user
oauth2:
  google:
    client_id: null
    client_secret: null
    redirect_uri: null
  microsoft:
    client_id: null
    client_secret: null
    redirect_uri: null
    tenant_id: null
pre-authorized:
  emails:
  - melsby@gmail.com
