api_key: lzxcdijjqvg7us4atgk58g8av8la13vj
cookie:
  expiry_days: 30
  key: my-random-key
  name: my-random-name
credentials:
  usernames:
    jill.pearson:
      email: jill.pearson@example.com
      first_name: Jill
      last_name: Pearson
      logged_in: false
      password: $2b$12$V8cPDMmb9/L/MvoYGhwhRe.GqSCkRUFvRcd1BQ92hPcADbeEsy8eC
      password_hint: Treat school fact he authority.
      roles:
      - user
    jsmith:
      email: john.smith@test.com
      first_name: Jhonny
      last_name: testest
      logged_in: false
      password: $2b$12$oONHePdrhtbO/n/4kRVome646cSWVNkqHBkz.PQGTBf7mQmG7vbhm
      password_hint: A very simple number...
      roles:
      - user
      - admin
    lawrence.gordon:
      email: lawrence.gordon@example.com
      first_name: Lawrence
      last_name: Gordon
      logged_in: false
      password: $2b$12$i45xCY1wcaBj6HVbMf7/nuVEkKnX8nORzvvK/XgKaYi3ol6yObGxK
      password_hint: Price food do pay plant.
      roles:
      - user
    tammy.sanchez:
      email: tammy.sanchez@example.com
      first_name: Tammy
      last_name: Sanchez
      logged_in: false
      password: $2b$12$i17bf05Js3mSS9ZMRGJ9Je9F5rpDWgoO/8N.amOnNkJr9y.a2LxsK
      password_hint: Lawyer however summer population.
      roles:
      - user
    tstgg:
      email: test@gmail.com
      first_name: test
      last_name: test
      logged_in: false
      password: $2b$12$hQLVkmc9wzHESRffclG6duD06gN.EgXHRxt.GQdesKWeOm0zycIKe
      password_hint: Test1234?
      roles:
      - user
      - admin
    veronica.dillon:
      email: veronica.dillon@example.com
      first_name: Veronica
      last_name: Dillon
      logged_in: false
      password: $2b$12$2r0yYssPz8vK3.PfieOCouKDcLiFOvkiIzFLkErxak4MGqZGQu0F2
      password_hint: Option light report law side.
      roles:
      - user
oauth2:
  google:
    client_id: null
    client_secret: null
    redirect_uri: null
  microsoft:
    client_id: null
    client_secret: null
    redirect_uri: null
    tenant_id: null
pre-authorized:
  emails:
  - melsby@gmail.com
