api_key: lzxcdijjqvg7us4atgk58g8av8la13vj
cookie:
  expiry_days: 30
  key: my-random-key
  name: my-random-name
credentials:
  usernames:
    jill.pearson:
      email: jill.pearson@example.com
      first_name: Jill
      last_name: Pearson
      logged_in: false
      password: '@7Xz#'
      password_hint: Treat school fact he authority.
      roles:
      - user
    jsmith:
      email: john.smith@test.com
      first_name: John
      last_name: Smith
      logged_in: false
      password: '123'
      password_hint: A very simple number...
      roles:
      - user
      - admin
    lawrence.gordon:
      email: lawrence.gordon@example.com
      first_name: Lawrence
      last_name: Gordon
      logged_in: false
      password: t#6Sk
      password_hint: Price food do pay plant.
      roles:
      - user
    tammy.sanchez:
      email: tammy.sanchez@example.com
      first_name: Tammy
      last_name: Sanchez
      logged_in: false
      password: '*76Ov'
      password_hint: Lawyer however summer population.
      roles:
      - user
    veronica.dillon:
      email: veronica.dillon@example.com
      first_name: Veronica
      last_name: Dillon
      logged_in: false
      password: $9Wah
      password_hint: Option light report law side.
      roles:
      - user
oauth2:
  google:
    client_id: null
    client_secret: null
    redirect_uri: null
  microsoft:
    client_id: null
    client_secret: null
    redirect_uri: null
    tenant_id: null
pre-authorized:
  emails:
  - melsby@gmail.com
