api_key: lzxcdijjqvg7us4atgk58g8av8la13vj
cookie:
  expiry_days: 30
  key: my-random-key
  name: my-random-name
credentials:
  usernames:
    benjamin.davis:
      email: benjamin.davis@example.com
      first_name: Benjamin
      last_name: Davis
      logged_in: false
      password: g$9Rz
      password_hint: ''
      roles:
      - user
    bonnie.brown:
      email: bonnie.brown@example.com
      first_name: Bonnie
      last_name: Brown
      logged_in: false
      password: h^8Nf
      password_hint: ''
      roles:
      - user
    caleb.moore:
      email: caleb.moore@example.com
      first_name: Caleb
      last_name: Moore
      logged_in: false
      password: )C2Xa
      password_hint: ''
      roles:
      - user
    cathy.lambert:
      email: cathy.lambert@example.com
      first_name: Cathy
      last_name: Lambert
      logged_in: false
      password: +4CsZ
      password_hint: ''
      roles:
      - user
    christopher.frazier:
      email: christopher.frazier@example.com
      first_name: Christopher
      last_name: Frazier
      logged_in: false
      password: G+9Io
      password_hint: ''
      roles:
      - user
    crystal.conway:
      email: crystal.conway@example.com
      first_name: Crystal
      last_name: Conway
      logged_in: false
      password: _r1Fd
      password_hint: ''
      roles:
      - user
    elizabeth.anderson:
      email: elizabeth.anderson@example.com
      first_name: Elizabeth
      last_name: Anderson
      logged_in: false
      password: j$1Md
      password_hint: ''
      roles:
      - user
    jackie.johnson:
      email: jackie.johnson@example.com
      first_name: Jackie
      last_name: Johnson
      logged_in: false
      password: 8*7Rw
      password_hint: ''
      roles:
      - user
    jacob.bailey:
      email: jacob.bailey@example.com
      first_name: Jacob
      last_name: Bailey
      logged_in: false
      password: )4S!r
      password_hint: ''
      roles:
      - user
    jacob.boyd:
      email: jacob.boyd@example.com
      first_name: Jacob
      last_name: Boyd
      logged_in: false
      password: a_0Gw
      password_hint: ''
      roles:
      - user
    jade.fox:
      email: jade.fox@example.com
      first_name: Jade
      last_name: Fox
      logged_in: false
      password: ^8SPu
      password_hint: ''
      roles:
      - user
    james.johnson:
      email: james.johnson@example.com
      first_name: James
      last_name: Johnson
      logged_in: false
      password: (2AoN
      password_hint: ''
      roles:
      - user
    james.pacheco:
      email: james.pacheco@example.com
      first_name: James
      last_name: Pacheco
      logged_in: false
      password: '%7Nrl'
      password_hint: ''
      roles:
      - user
    james.white:
      email: james.white@example.com
      first_name: James
      last_name: White
      logged_in: false
      password: '#0G$o'
      password_hint: ''
      roles:
      - user
    jared.livingston:
      email: jared.livingston@example.com
      first_name: Jared
      last_name: Livingston
      logged_in: false
      password: '@1RPa'
      password_hint: ''
      roles:
      - user
    jason.wallace:
      email: jason.wallace@example.com
      first_name: Jason
      last_name: Wallace
      logged_in: false
      password: (1Wgc
      password_hint: ''
      roles:
      - user
    jennifer.allison:
      email: jennifer.allison@example.com
      first_name: Jennifer
      last_name: Allison
      logged_in: false
      password: '%1Wlo'
      password_hint: ''
      roles:
      - user
    jeremy.jackson:
      email: jeremy.jackson@example.com
      first_name: Jeremy
      last_name: Jackson
      logged_in: false
      password: I@7Dm
      password_hint: ''
      roles:
      - user
    jessica.lewis:
      email: jessica.lewis@example.com
      first_name: Jessica
      last_name: Lewis
      logged_in: false
      password: '*1AsL'
      password_hint: ''
      roles:
      - user
    jessica.logan:
      email: jessica.logan@example.com
      first_name: Jessica
      last_name: Logan
      logged_in: false
      password: J!5Bo
      password_hint: ''
      roles:
      - user
    john.decker:
      email: john.decker@example.com
      first_name: John
      last_name: Decker
      logged_in: false
      password: $9Mdw
      password_hint: ''
      roles:
      - user
    jonathan.washington:
      email: jonathan.washington@example.com
      first_name: Jonathan
      last_name: Washington
      logged_in: false
      password: $1FQv
      password_hint: ''
      roles:
      - user
    joseph.stephens:
      email: joseph.stephens@example.com
      first_name: Joseph
      last_name: Stephens
      logged_in: false
      password: '%K0Yu'
      password_hint: ''
      roles:
      - user
    laurie.ramirez:
      email: laurie.ramirez@example.com
      first_name: Laurie
      last_name: Ramirez
      logged_in: false
      password: )7Xtw
      password_hint: ''
      roles:
      - user
    luke.anderson:
      email: luke.anderson@example.com
      first_name: Luke
      last_name: Anderson
      logged_in: false
      password: n(7Xy
      password_hint: ''
      roles:
      - user
    mary.morris:
      email: mary.morris@example.com
      first_name: Mary
      last_name: Morris
      logged_in: false
      password: )l6Rd
      password_hint: ''
      roles:
      - user
    nicole.whitehead:
      email: nicole.whitehead@example.com
      first_name: Nicole
      last_name: Whitehead
      logged_in: false
      password: +9FOs
      password_hint: ''
      roles:
      - user
    stephen.shaw:
      email: stephen.shaw@example.com
      first_name: Stephen
      last_name: Shaw
      logged_in: false
      password: '!4sZm'
      password_hint: ''
      roles:
      - user
    travis.gilmore:
      email: travis.gilmore@example.com
      first_name: Travis
      last_name: Gilmore
      logged_in: false
      password: )7TBj
      password_hint: ''
      roles:
      - user
    vanessa.castro:
      email: vanessa.castro@example.com
      first_name: Vanessa
      last_name: Castro
      logged_in: false
      password: '%2Kpi'
      password_hint: ''
      roles:
      - user
oauth2:
  google:
    client_id: null
    client_secret: null
    redirect_uri: null
  microsoft:
    client_id: null
    client_secret: null
    redirect_uri: null
    tenant_id: null
pre-authorized:
  emails:
  - melsby@gmail.com
