api_key: lzxcdijjqvg7us4atgk58g8av8la13vj
cookie:
  expiry_days: 30
  key: my-random-key
  name: my-random-name
credentials:
  usernames:
    fabg:
      email: f.test@gmail.com
      first_name: Florian
      last_name: abgrall
      logged_in: false
      password: $2b$12$cO4EOZ3kcQ7jJmjnQpbTf.pBGPgGzRKKm3XtAdv2C9fOe5x9DPhpG
      password_hint: admin
      roles:
      - user
      - admin
    jsmith:
      email: test9r@gmail.com
      failed_login_attempts: 0
      first_name: heyhey
      last_name: Smith
      logged_in: false
      password: $2b$12$8ukAfDSgU9RaP2yBJRwF8uk2frpTkbYsprJTmq68raHiA4InQql.u
      password_hint: admin
      roles:
      - admin
      - user
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      first_name: Rebecca
      last_name: Briggs
      logged_in: false
      password: $2b$12$GJKJ7GSxjWaEUGj3qFqHluE5xexAACd5OPjfm7TQRYqG4V5rJ2v6e
      password_hint: admin
      roles:
      - user
    teggst:
      email: tseets@tsgt.com
      first_name: teset
      last_name: etest
      logged_in: false
      password: $2b$12$wSzRkpgP52roXj4.xDummermQUj47ageafH9jQjIfv9PdVKu9MCzq
      password_hint: Tsgt1234?
      roles:
      - user
      - admin
oauth2:
  google:
    client_id: null
    client_secret: null
    redirect_uri: null
  microsoft:
    client_id: null
    client_secret: null
    redirect_uri: null
    tenant_id: null
pre-authorized:
  emails:
  - melsby@gmail.com
