api_key: lzxcdijjqvg7us4atgk58g8av8la13vj
cookie:
  expiry_days: 30
  key: my-random-key
  name: my-random-name
credentials:
  usernames:
    jsmith:
      email: john.smith@test.com
      first_name: John
      last_name: Smith
      logged_in: false
      password: '123'
      password_hint: A very simple number...
      roles:
      - user
      - admin
    kelsey.bailey:
      email: kelsey.bailey@example.com
      first_name: Kelsey
      last_name: Bailey
      logged_in: false
      password: '&0Caz'
      password_hint: Citizen check should office wide.
      roles:
      - user
    michelle.callahan:
      email: michelle.callahan@example.com
      first_name: Michelle
      last_name: Callahan
      logged_in: false
      password: Z*1Wo
      password_hint: Near degree side take.
      roles:
      - user
    tina.flores:
      email: tina.flores@example.com
      first_name: Tina
      last_name: Flores
      logged_in: false
      password: $9Xa(
      password_hint: New view officer.
      roles:
      - user
    tonya.lopez:
      email: tonya.lopez@example.com
      first_name: Tonya
      last_name: Lopez
      logged_in: false
      password: $4Fhf
      password_hint: Three protect bed quite traditional.
      roles:
      - user
oauth2:
  google:
    client_id: null
    client_secret: null
    redirect_uri: null
  microsoft:
    client_id: null
    client_secret: null
    redirect_uri: null
    tenant_id: null
pre-authorized:
  emails:
  - melsby@gmail.com
