api_key: lzxcdijjqvg7us4atgk58g8av8la13vj
cookie:
  expiry_days: 30
  key: my-random-key
  name: my-random-name
credentials:
  usernames:
    evelyn.ramirez:
      email: evelyn.ramirez@example.com
      first_name: Evelyn
      last_name: Ramirez
      logged_in: false
      password: (1Iq#
      password_hint: Voice attention discover add.
      roles:
      - user
    jsmith:
      email: john.smith@test.com
      first_name: John
      last_name: Smith
      logged_in: false
      password: '123'
      password_hint: A very simple number...
      roles:
      - user
      - admin
    rebecca.jones:
      email: rebecca.jones@example.com
      first_name: Rebecca
      last_name: Jones
      logged_in: false
      password: '*r9Ri'
      password_hint: Him than area when paper.
      roles:
      - user
    seth.smith:
      email: seth.smith@example.com
      first_name: Seth
      last_name: Smith
      logged_in: false
      password: o%1Ve
      password_hint: Responsibility ask station big.
      roles:
      - user
    susan.price:
      email: susan.price@example.com
      first_name: Susan
      last_name: Price
      logged_in: false
      password: '!@2Jx'
      password_hint: Admit would contain state.
      roles:
      - user
oauth2:
  google:
    client_id: null
    client_secret: null
    redirect_uri: null
  microsoft:
    client_id: null
    client_secret: null
    redirect_uri: null
    tenant_id: null
pre-authorized:
  emails:
  - melsby@gmail.com
